### ISSUE TITLE
where is acsv module that I can import

### ISSUE THREAD

**Issue by VisionTheta** [fepegar/ndPytools#1]
Hi, fernando

I noticed that in your ndPytools, you import acsv python module. However, I cannot find it in pip. I guess acsv file is used to read Nanozoomer's ndpa file. Could you share it in this repository?

**Comment by fepegar** [comment]
Hi @tt-leader,

I wrote the `acsv` module to handle annotation CSV files representing ROIs in [3D Slicer](https://www.slicer.org/wiki/Documentation/4.8/Modules/Annotations). I can share it if you need that, or you can just remove the `import`.

I uploaded the repo as a reference, not to be used directly. Sorry for the inconvenience.
