### ISSUE TITLE
Question about header infomation

### ISSUE THREAD

**Issue by Dxye** [fepegar/ndPytools#2]
Hi fepegar, I wonder that how can I get header. Is it generate from ndp.view or somewhere? Actually after execute Popen(['tifftopnm', '-headerdump', self.filepath], stdout=PIPE, stderr=STDOUT, shell = True), I get '-headerdump: tifftopnm: command not found'. Is tifftopnm a package I have to pip install or you make it yourself? Looking forward to your reply, thank you.

**Comment by fepegar** [comment]
Hy @Dxye,
[tifftopnm](http://netpbm.sourceforge.net/doc/tifftopnm.html) is installed in my Linux distribution. I don't know if it came by default. There must be similar tools for other platforms or some Python library that lets you read TIFF headers.

**Comment by Dxye** [comment]
Hi @fepegar ,
Thank u for ur reply. Finally I found [openslide](http://openslide.org/api/python/) can load ndpi file. Hope this is also useful for you :)
