### ISSUE TITLE
Can't use the tools to handle ndpi

### ISSUE THREAD

**Issue by BlueSpace-ice** [fepegar/ndPytools#3]
Sorry to bother you, I would like to use this code to read ndpi and convert it into a jpg file. After reading your code, I found that the ImageUtils in it may be a plugin you wrote yourself and was not uploaded. I hope you can teach me how to use this Python program or upload a complete project. Thank you!
<img width="549" alt="1706010396391" src="https://github.com/fepegar/ndPytools/assets/63438264/9c61d6f8-3bf6-40c4-98fe-22200e832366">

**Comment by fepegar** [comment]
Hi, @BlueSpace-ice. This is a very old project and I don't have access to that module anymore. I suggest you use https://openslide.org/api/python/ to process your NDPI files. Good luck!
